# Generated by Django 3.2.15 on 2022-10-29 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameraapp', '0003_auto_20221029_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, upload_to='founders'),
        ),
    ]
