# Generated by Django 3.2.15 on 2022-10-31 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameraapp', '0005_auto_20221030_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Callback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('email', models.EmailField(max_length=200)),
                ('Phone', models.IntegerField()),
                ('message', models.CharField(max_length=300, unique=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Call Back form',
                'verbose_name_plural': 'Call Back Forms',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('name',), 'verbose_name': 'Founder', 'verbose_name_plural': 'Founders'},
        ),
    ]
