# Generated by Django 3.2.15 on 2022-10-31 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameraapp', '0006_auto_20221031_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callback',
            name='created',
        ),
        migrations.RemoveField(
            model_name='callback',
            name='updated',
        ),
        migrations.AlterField(
            model_name='callback',
            name='message',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
