# Generated by Django 3.2.15 on 2022-10-31 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameraapp', '0008_alter_callback_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callback',
            name='Phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='callback',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='callback',
            name='message',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='callback',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
