# Generated by Django 3.2.15 on 2022-10-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameraapp', '0009_auto_20221031_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callback',
            name='message',
            field=models.TextField(),
        ),
    ]
