# Generated by Django 3.2.15 on 2022-10-31 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameraapp', '0010_alter_callback_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callback',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
