# Generated by Django 3.2.15 on 2022-10-31 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameraapp', '0011_alter_callback_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=100)),
            ],
            options={
                'verbose_name': 'Newsleter mails',
                'verbose_name_plural': 'Newsletter mails',
                'ordering': ('mail',),
            },
        ),
    ]
