# Generated by Django 3.2.15 on 2022-10-31 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameraapp', '0012_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='mailstore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
            ],
            options={
                'verbose_name': 'Newsleter mails',
                'verbose_name_plural': 'Newsletter mails',
                'ordering': ('email',),
            },
        ),
        migrations.DeleteModel(
            name='mail',
        ),
    ]
